version: '3.9'
services:
  backend:
    container_name: argos_backend
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    container_name: argos_db
    image: mysql
    platform: linux/armd64
    restart: always
    environment:
      MYSQL_DATABASE: argos
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  redis:
    container_name: argos_redis
    image: redis:latest
    ports:
      - 6379:6379
